import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-screen h-screen overflow-y-auto scrollbar-hidden containers`}
      >
        <div className="w-screen h-screen overflow-y-scroll snap-y snap-mandatory scrollbar-hidden containers">
          {children}
        </div>
      </body>
    </html>
  );
}
